INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 1 post', 'Recibirás esta insignia cuando publiques 1 post.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 10 posts', 'Recibirás esta insignia cuando publiques 10 posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 25 posts', 'Recibirás esta insignia cuando publiques 25 posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 50 posts', 'Recibirás esta insignia cuando publiques 50 posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,1K posts', 'Recibirás esta insignia cuando publiques 0,1K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,25K posts', 'Recibirás esta insignia cuando publiques 0,25K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,5K posts', 'Recibirás esta insignia cuando publiques 0,5K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 1K posts', 'Recibirás esta insignia cuando publiques 1K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 2,5K posts', 'Recibirás esta insignia cuando publiques 2,5K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 5K posts', 'Recibirás esta insignia cuando publiques 5K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 10K posts', 'Recibirás esta insignia cuando publiques 10K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 15K posts', 'Recibirás esta insignia cuando publiques 15K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 25K posts', 'Recibirás esta insignia cuando publiques 25K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 50K posts', 'Recibirás esta insignia cuando publiques 50K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 100K posts', 'Recibirás esta insignia cuando publiques 100K posts.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 1 post', 'Recibirás esta insignia cuando publiques 1 post propio.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 10 posts', 'Recibirás esta insignia cuando publiques 10 posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 25 posts', 'Recibirás esta insignia cuando publiques 50 posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 50 posts', 'Recibirás esta insignia cuando publiques 50 posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,1K posts', 'Recibirás esta insignia cuando publiques 0,1K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,25K posts', 'Recibirás esta insignia cuando publiques 0,25K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 0,5K posts', 'Recibirás esta insignia cuando publiques 0,5K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 1K posts', 'Recibirás esta insignia cuando publiques 1K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 2,5K posts', 'Recibirás esta insignia cuando publiques 2,5K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 5K posts', 'Recibirás esta insignia cuando publiques 5K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 10K posts', 'Recibirás esta insignia cuando publiques 10K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 15K posts', 'Recibirás esta insignia cuando publiques 15K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 25K posts', 'Recibirás esta insignia cuando publiques 25K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 50K posts', 'Recibirás esta insignia cuando publiques 50K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Posts]: 100K posts', 'Recibirás esta insignia cuando publiques 100K posts propios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 1 comentario', 'Recibirás esta insignia cuando publiques 1 comentario.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 10 comentarios', 'Recibirás esta insignia cuando publiques 10 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 50 comentarios', 'Recibirás esta insignia cuando publiques 50 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 50 comentarios', 'Recibirás esta insignia cuando publiques 50 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 0,1K comentarios', 'Recibirás esta insignia cuando publiques 100 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 0,25K comentarios', 'Recibirás esta insignia cuando publiques 250 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 0,5K comentarios', 'Recibirás esta insignia cuando publiques 500 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 1K comentarios', 'Recibirás esta insignia cuando publiques 1000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 2,5K comentarios', 'Recibirás esta insignia cuando publiques 2500 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 5K comentarios', 'Recibirás esta insignia cuando publiques 5000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 10K comentarios', 'Recibirás esta insignia cuando publiques 10000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 15K comentarios', 'Recibirás esta insignia cuando publiques 15000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 25K comentarios', 'Recibirás esta insignia cuando publiques 25000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 50K comentarios', 'Recibirás esta insignia cuando publiques 50000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Comentarios]: 100K comentarios', 'Recibirás esta insignia cuando publiques 100000 comentarios.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 1 punto de karma', 'Recibirás esta insignia cuando tengas 1 voto positivo.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 5 puntos de karma', 'Recibirás esta insignia cuando tengas 5 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 10 puntos de karma', 'Recibirás esta insignia cuando tengas 10 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 50 puntos de karma', 'Recibirás esta insignia cuando tengas 50 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 100 puntos de karma', 'Recibirás esta insignia cuando tengas 100 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 250 puntos de karma', 'Recibirás esta insignia cuando tengas 250 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 500 puntos de karma', 'Recibirás esta insignia cuando tengas 500 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 1000 puntos de karma', 'Recibirás esta insignia cuando tengas 1000 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -1 punto de karma', 'Recibirás esta insignia cuando tengas 1 voto negativo.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -5 puntos de karma', 'Recibirás esta insignia cuando tengas 5 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -10 puntos de karma', 'Recibirás esta insignia cuando tengas 10 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -50 puntos de karma', 'Recibirás esta insignia cuando tengas 50 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -0,1K puntos de karma', 'Recibirás esta insignia cuando tengas 100 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -0,25K puntos de karma', 'Recibirás esta insignia cuando tengas 250 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -0,5K puntos de karma', 'Recibirás esta insignia cuando tengas 500 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -1K puntos de karma', 'Recibirás esta insignia cuando tengas 1000 votos negativos. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 0.01 puntos de karma por día', 'Recibirás esta insignia cuando tengas 0.01 puntos de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 0.5 puntos de karma por día', 'Recibirás esta insignia cuando tengas 0.5 puntos de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 1 punto de karma por día', 'Recibirás esta insignia cuando tengas 1 punto de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 2.5 puntos de karma por día', 'Recibirás esta insignia cuando tengas 2.5 puntos de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 5 puntos de karma por día', 'Recibirás esta insignia cuando tengas 5 puntos de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 10 puntos de karma por día', 'Recibirás esta insignia cuando tengas 10 puntos de karma por día. Si te das cuenta ya es mucho.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -0.01 puntos de karma por día', 'Recibirás esta insignia cuando tengas -0.01 puntos de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -0.5 puntos de karma por día', 'Recibirás esta insignia cuando tengas -0.5 puntos de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -1 punto de karma por día', 'Recibirás esta insignia cuando tengas -1 punto de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -2.5 puntos de karma por día', 'Recibirás esta insignia cuando tengas -2.5 puntos de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -5 puntos de karma por día', 'Recibirás esta insignia cuando tengas -5 puntos de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -10 puntos de karma por día', 'Recibirás esta insignia cuando tengas -10 puntos de karma por día. ¡Cuidado con ser baneado!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 1 día Online', 'Recibirás esta insignia cuando hayas estado 1 día Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 1 semana Online', 'Recibirás esta insignia cuando hayas estado 1 semana Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 1 quincena Online', 'Recibirás esta insignia cuando hayas estado 1 quincena Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 1 mes Online', 'Recibirás esta insignia cuando hayas estado 1 mes Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 3 meses Online', 'Recibirás esta insignia cuando hayas estado 3 meses Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: medio año Online', 'Recibirás esta insignia cuando hayas estado medio año Online.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Online]: 1 año Online', 'Recibirás esta insignia cuando hayas estado 1 año Online (365 días).', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 1 día registrado', 'Recibirás esta insignia cuando hayas estado 1 día registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 1 semana registrado', 'Recibirás esta insignia cuando hayas estado 1 semana registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 1 quincena registrado', 'Recibirás esta insignia cuando hayas estado 1 quincena registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 1 mes registrado', 'Recibirás esta insignia cuando hayas estado 1 mes registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 3 meses registrado', 'Recibirás esta insignia cuando hayas estado 3 meses registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: medio año registrado', 'Recibirás esta insignia cuando hayas estado medio año registrado.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 1 año registrado', 'Recibirás esta insignia cuando hayas estado 1 año registrado (365 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 2 años registrado', 'Recibirás esta insignia cuando hayas estado 2 años registrado (730 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 3 años registrado', 'Recibirás esta insignia cuando hayas estado 3 años registrado (1095 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 4 años registrado', 'Recibirás esta insignia cuando hayas estado 4 años registrado (1460 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 5 años registrado', 'Recibirás esta insignia cuando hayas estado 5 años registrado (1825 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 6 años registrado', 'Recibirás esta insignia cuando hayas estado 6 años registrado (2190 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 7 años registrado', 'Recibirás esta insignia cuando hayas estado 7 años registrado (2555 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 8 años registrado', 'Recibirás esta insignia cuando hayas estado 8 años registrado (2920 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 9 años registrado', 'Recibirás esta insignia cuando hayas estado 9 años registrado (3285 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Tiempo Registrado]: 10 años registrado', 'Recibirás esta insignia cuando hayas estado 10 años registrado (3650 días). ¡Esperemos que sean muchos más!', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1 NexusPoints', 'Recibirás esta insignia cuando tengas 1 NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 0,5K NexusPoints', 'Recibirás esta insignia cuando tengas 0,5K NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1K NexusPoints', 'Recibirás esta insignia cuando tengas 1K NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 10K NexusPoints', 'Recibirás esta insignia cuando tengas 10K NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 100K NexusPoints', 'Recibirás esta insignia cuando tengas 100K NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 500K NexusPoints', 'Recibirás esta insignia cuando tengas medio millón de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1M NexusPoints', 'Recibirás esta insignia cuando tengas 1M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 2,5M NexusPoints', 'Recibirás esta insignia cuando tengas 2,5M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 5M NexusPoints', 'Recibirás esta insignia cuando tengas 5M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 10M NexusPoints', 'Recibirás esta insignia cuando tengas 10M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 25M NexusPoints', 'Recibirás esta insignia cuando tengas 25M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 50M NexusPoints', 'Recibirás esta insignia cuando tengas 50M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 100M NexusPoints', 'Recibirás esta insignia cuando tengas 100M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 250M NexusPoints', 'Recibirás esta insignia cuando tengas 250M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 500M NexusPoints', 'Recibirás esta insignia cuando tengas 500M de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1B NexusPoints', 'Recibirás esta insignia cuando tengas 1B de NexusPoints en la cartera.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1 NexusPoints', 'Recibirás esta insignia cuando tengas 1 NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 0,5K NexusPoints', 'Recibirás esta insignia cuando tengas 0,5K NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1K NexusPoints', 'Recibirás esta insignia cuando tengas 1K NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 10K NexusPoints', 'Recibirás esta insignia cuando tengas 10K NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 100K NexusPoints', 'Recibirás esta insignia cuando tengas 100K NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 500K NexusPoints', 'Recibirás esta insignia cuando tengas medio millón de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1M NexusPoints', 'Recibirás esta insignia cuando tengas 1M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 2,5M NexusPoints', 'Recibirás esta insignia cuando tengas 2,5M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 5M NexusPoints', 'Recibirás esta insignia cuando tengas 5M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 10M NexusPoints', 'Recibirás esta insignia cuando tengas 10M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 25M NexusPoints', 'Recibirás esta insignia cuando tengas 25M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 50M NexusPoints', 'Recibirás esta insignia cuando tengas 50M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 100M NexusPoints', 'Recibirás esta insignia cuando tengas 100M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 250M NexusPoints', 'Recibirás esta insignia cuando tengas 250M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 500M NexusPoints', 'Recibirás esta insignia cuando tengas 500M de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[NexusPoints]: 1B NexusPoints', 'Recibirás esta insignia cuando tengas 1B de NexusPoints en el banco.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: 25 puntos de karma', 'Recibirás esta insignia cuando tengas 25 votos positivos.', '');
INSERT INTO badges (badge_name, badge_description, badge_img) VALUES ('[Karma]: -25 puntos de karma', 'Recibirás esta insignia cuando tengas 25 votos negativos. ¡Cuidado con ser baneado!', '');
